[project]
name = ""
version = ""
description = ""
authors = [
]
dependencies = [
    "loguru>=0.6.0",
    "docstring-parser>=0.14.1",
    "xoa-driver>=1.0.8",
]
requires-python = ">=3.10"
license = {}
[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
